/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dl4jdream;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author psyriccio
 */
public class MainFrame extends javax.swing.JFrame {

  private final int panWidth = 800;
  private final int panHeight = 600;
  private final int bottomPadHeight = 30;
  
  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    initComponents();
    uiSetup();
    try {
      ((ImagePanel) jImagePanel).setImage(ImageIO.read(new File("./img/sample.jpg")));
    } catch (IOException ex) {
      Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void uiSetup() {
    setSize(panHeight, panHeight + bottomPadHeight);
    setPreferredSize(new Dimension(panWidth, panHeight + bottomPadHeight));
    setMaximumSize(new Dimension(panWidth, panHeight + bottomPadHeight));
    jImagePanel.setSize(panWidth, panHeight);
    pack();
    setResizable(false);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTestButton = new javax.swing.JButton();
    jImagePanel = new ImagePanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTestButton.setText("Test");
    jTestButton.setAlignmentY(0.0F);
    jTestButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTestButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jImagePanelLayout = new javax.swing.GroupLayout(jImagePanel);
    jImagePanel.setLayout(jImagePanelLayout);
    jImagePanelLayout.setHorizontalGroup(
      jImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jImagePanelLayout.setVerticalGroup(
      jImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 436, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 597, Short.MAX_VALUE)
        .addComponent(jTestButton))
      .addComponent(jImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTestButton))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestButtonActionPerformed
    jTestButton.setEnabled(false);
    new MainTest().doTest();
    jTestButton.setEnabled(true);
  }//GEN-LAST:event_jTestButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jImagePanel;
  private javax.swing.JButton jTestButton;
  // End of variables declaration//GEN-END:variables
}
